// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Dish {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  category?: string;
  description?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  tags?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  publication?: string;
  date?: string;
  link?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  tag?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Offer {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  lead?: string;
  body?: string;
  cta_text?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    dishes: Dish;
    posts: Post;
    offers: Offer;
  }
}
